title: Value Cards
description: An Educational Toolkit for Teaching Social Impacts of Machine Learning through Deliberation
show_downloads: false
cover-img: "https://octodex.github.com/images/yaktocat.png"
theme: jekyll-theme-cayman

